// ============================================================
// 등록/해제/중지 스크립트 — '스테이션 열기.cmd'와 상태 페이지(⚙ 설정)가 호출한다
//  기본:     자동시작 등록(갱신) + 바탕화면 바로가기 + 스테이션 열기 (멱등)
//  --stop:   스테이션 닫기 (서버는 유지)
//  --remove: 시작프로그램·바로가기 제거 + 스테이션 닫기
// ============================================================
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import http from 'node:http';
import { spawn, execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const WATCHDOG = path.join(HERE, 'watchdog.mjs');
const PID_FILE = path.join(HERE, 'logs', 'watchdog.pid');
const NODE = process.execPath;
const STARTUP_DIR = path.join(process.env.APPDATA, 'Microsoft', 'Windows', 'Start Menu', 'Programs', 'Startup');
const STARTUP_VBS = path.join(STARTUP_DIR, 'MigManager-Watchdog.vbs');
const OLD_STARTUP_CMD = path.join(STARTUP_DIR, 'MigManager-Watchdog.cmd'); // 구버전(창 뜨는 방식) 항목
const URL_NAME = '서버 상태.url';

function controlPort() {
  try {
    return JSON.parse(fs.readFileSync(path.join(HERE, 'servers.config.json'), 'utf8')).controlPort || 3738;
  } catch {
    return 3738;
  }
}

// OneDrive 바탕화면 리디렉션까지 고려해 실제 바탕화면 경로를 찾는다
function desktopDir() {
  try {
    const out = execFileSync('reg', [
      'query', 'HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\User Shell Folders', '/v', 'Desktop',
    ], { encoding: 'utf8', windowsHide: true });
    const m = out.match(/Desktop\s+REG(?:_EXPAND)?_SZ\s+(.+)/);
    if (m) {
      const p = m[1].trim().replace(/%([^%]+)%/g, (_, v) => process.env[v] || '');
      if (fs.existsSync(p)) return p;
    }
  } catch { /* fallback */ }
  return path.join(os.homedir(), 'Desktop');
}

function pingControl(port) {
  return new Promise((resolve) => {
    const req = http.get({ host: '127.0.0.1', port, path: '/api/status', timeout: 1500 }, (res) => {
      res.resume();
      resolve(true);
    });
    req.on('timeout', () => { req.destroy(); resolve(false); });
    req.on('error', () => resolve(false));
  });
}

function killWatchdogByPidFile() {
  try {
    const pid = Number(fs.readFileSync(PID_FILE, 'utf8').trim());
    if (pid > 4) { process.kill(pid); return pid; }
  } catch { /* 없거나 이미 종료됨 */ }
  return null;
}

const port = controlPort();
const desktop = desktopDir();
const urlFileContent = `[InternetShortcut]\r\nURL=http://localhost:${port}\r\nIconFile=C:\\Windows\\System32\\SHELL32.dll\r\nIconIndex=13\r\n`;
// 로그인 시 스테이션을 '창 없이' 실행하는 VBS (경로는 설치 시점에 절대경로로 박힌다)
// 주의: wscript 는 VBS 를 ANSI 로 읽으므로 내용은 ASCII 로만 작성한다
const startupVbsContent = [
  `' MigManager watchdog auto-start (no window) - generated by server-control/setup.mjs`,
  `Dim sh`,
  `Set sh = CreateObject("WScript.Shell")`,
  `sh.Run Chr(34) & "${NODE}" & Chr(34) & " " & Chr(34) & "${WATCHDOG}" & Chr(34), 0, False`,
  ``,
].join('\r\n');

// 스테이션 닫기 (서버는 유지) — 설정 패널의 [서버관리 종료]가 호출
if (process.argv.includes('--stop')) {
  const pid = killWatchdogByPidFile();
  if (pid) {
    try { fs.unlinkSync(PID_FILE); } catch { /* ignore */ }
    console.log(`스테이션(pid ${pid})을 닫았습니다. 이미 켜 둔 서버는 계속 돌아갑니다.`);
    console.log('(닫혀 있는 동안에는 상태 감시가 멈춥니다)');
  } else {
    console.log('스테이션이 이미 닫혀 있습니다.');
  }
  console.log("다시 열려면: '스테이션 열기.cmd'");
  process.exit(0);
}

if (process.argv.includes('--remove')) {
  let removed = 0;
  for (const f of [STARTUP_VBS, OLD_STARTUP_CMD, path.join(desktop, URL_NAME), path.join(HERE, URL_NAME)]) {
    if (fs.existsSync(f)) { fs.unlinkSync(f); removed++; console.log('삭제됨: ' + f); }
  }
  const pid = killWatchdogByPidFile();
  console.log(pid ? `스테이션(pid ${pid})을 닫았습니다.` : '열려 있는 스테이션이 없습니다.');
  console.log('\n자동시작 해제 완료. 이미 켜져 있는 서버는 그대로 돌아갑니다.');
  console.log("다시 쓰려면 '스테이션 열기.cmd'를 실행하면 됩니다.");
  process.exit(0);
}

// 1) 시작프로그램 등록 (로그인 시 스테이션 자동 실행 — 창 없음)
if (fs.existsSync(OLD_STARTUP_CMD)) {
  fs.unlinkSync(OLD_STARTUP_CMD);
  console.log('      (구버전 시작프로그램 항목을 교체했습니다)');
}
fs.writeFileSync(STARTUP_VBS, startupVbsContent);
console.log('[1/3] 자동 시작 등록 완료 — 이미 있으면 갱신됩니다 (창 없이 백그라운드 실행)');
console.log('      ' + STARTUP_VBS);

// 2) 바탕화면 바로가기
try {
  fs.writeFileSync(path.join(desktop, URL_NAME), urlFileContent);
  console.log('[2/3] 바탕화면 바로가기 생성: ' + path.join(desktop, URL_NAME));
} catch (e) {
  console.log('[2/3] 바탕화면 바로가기 생성 실패(' + e.message + ') — server-control 폴더의 바로가기를 복사해 쓰세요.');
}
fs.writeFileSync(path.join(HERE, URL_NAME), urlFileContent); // 폴더 안에도 예비로 하나

// 3) 스테이션 즉시 실행 + 관제 페이지 열기
const already = await pingControl(port);
if (already) {
  console.log('[3/3] 스테이션이 이미 열려 있습니다.');
} else {
  spawn('wscript.exe', [STARTUP_VBS], { detached: true, stdio: 'ignore', windowsHide: true }).unref();
  console.log('[3/3] 스테이션을 열었습니다. (창 없이 백그라운드로 돕니다)');
}
spawn(`start "" "http://localhost:${port}"`, { shell: true, detached: true, stdio: 'ignore', windowsHide: true }).unref();

console.log(`
========================================================
 MIG Station 준비 완료!
 - 상태 페이지:  http://localhost:${port}  (바탕화면 '서버 상태' 아이콘)
 - '스테이션 열기.cmd'는 언제 다시 실행해도 안전합니다.
   (등록 갱신 + 꺼져 있으면 켜기 + 상태 페이지 열기)
 - 서버관리 종료는 상태 페이지의 ⚙ 서버 설정에 있습니다.
 - 완전 제거(등록·아이콘 삭제)는: node setup.mjs --remove
 - 재부팅 후에는 아무나 로그인만 하면 자동으로 복구됩니다.
========================================================`);
